### ISSUE TITLE
Selected event?

### ISSUE THREAD

**Issue by focussing** [charliekassel/vuejs-autocomplete#1]
Is there a "selected" event or similar which is fired when the user selects an item?

**Comment by charliekassel** [comment]
There is @focussing - but currently undocumented.

https://github.com/charliekassel/vuejs-autocomplete/blob/master/src/components/Autocomplete.vue#L305-L309

**Comment by focussing** [comment]
That did it, thanks!
If you want I can post a little piece of demo code here.

**Comment by charliekassel** [comment]
Happy to accept a PR to the readme - available events table perhaps?

**Comment by ronnievisser** [comment]
please share this demo code. I have no idea how to trigger the selected event

**Comment by charliekassel** [comment]
I've updated the readme with an events table - also added a full example which should clarify things for you.

**Comment by ronnievisser** [comment]
Thanks. this clears things up!!
