### ISSUE TITLE
How to keep input text when click outside?

### ISSUE THREAD

**Issue by duet-ngyen** [charliekassel/vuejs-autocomplete#18]
When I typing `He`, list suggestion is `Hello`, `Hello World`. 
When click outside the result. The input `He` was cleared. How can I keep it on?

**Comment by charliekassel** [comment]
The behaviour here is that as an option has not been specifically selected then `He` is not a valid option - therefore it will be cleared.

**Comment by riksnelders** [comment]
Makes no sense.. Can u please implement this? I want to make it easier for the user to pick an existing company for example. But add to data when its not present. Not possible now.

**Comment by charliekassel** [comment]
As designed. I don't want a value that is invalid.

**Comment by riksnelders** [comment]
Then make it configurable. And set default to false?

**Comment by charliekassel** [comment]
No thank you, that behaviour does not make sense to me, I don’t want to support it.

**Comment by richardfeliciano** [comment]
> No thank you, that behaviour does not make sense to me, I don’t want to support it.
Make sense to a lot of people.

**Comment by grinevri** [comment]
I think it is possible to handle that by setting properly the `resultsValue`, `initialDisplay` properties and, `selected` event.
