### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by focussing** [charliekassel/vuejs-autocomplete#2]
I am using your datepicker and autocomplete parts side by side with no formatting.

```
<div class="column is-3">
  <datepicker v-model="endDate" :monday-first="true" input-class="input" placeholder="Selecteer..." v-on:selected="doSelection()"></datepicker>
 </div>

<div class="column is-3">
  <autocomplete is-size-1 :source="vehicleItems" v-on:selected="vehicleSelected($event)">
  </autocomplete>
</div>
```
Resulting in this
![schermafbeelding 2017-09-13 om 12 23 40](https://user-images.githubusercontent.com/26736152/30376733-b27422f2-988d-11e7-82a7-e08823735901.png)

How can I style the autocomplete same as datepicker?

**Comment by charliekassel** [comment]
The component offers only basic css formatting so as to attempt to be less opinionated - this is left to the user to style how they see fit.

Closing as this is a css question - not really related to the component.

**Comment by focussing** [comment]
OK, understand that, let me phrase otherwise:

Why is the styling of your datepicker and autocomplete parts different?
Could you either style it identical, or remove all styling? Then at least they would look the same, and the user can style them as he want to.
