### ISSUE TITLE
Send post instead of get?

### ISSUE THREAD

**Issue by goors** [charliekassel/vuejs-autocomplete#24]
I see that you are checking options first in rest request, but how do you do post? 
Guess you can not do post right?

**Comment by charliekassel** [comment]
No, I don't see the need really - it's reading data so that should only be a GET.

**Comment by goors** [comment]
Some apis dont' have GET for this kind of things. SO you should add this stuff.

**Comment by charliekassel** [comment]
It's a valid point, but it just seems wrong to support poor api design...

**Comment by goors** [comment]
At company of 6mil euros, yes it is wrong ....

**Comment by charliekassel** [comment]
I'm happy to leave this open to see what reaction we get from the community on this.

**Comment by Raiondesu** [comment]
@charliekassel, even though you're right about POST for information requests being a bad design, there's no need to enforce anything on the end-users.

I can also say that enforcing using `fetch`, `json` and `lodash` under the hood is a very bad design too (there are many use-cases in which these "enforcement" things are a pain for a developer). Things like this are the main reason why enforcing certain behaviours is considered toxic among developers.

@goors certainly is not alone in his request (take me for example). And it's (at least) unfair to blame people for bad design while also defending your own bad design, @charliekassel. 

I don't see any reason for keeping this issue open or not implementing requested changes (as these would be, actually, backwards compatible).

P.S. Consider this a community reaction you waited for.

**Comment by kaskar2008** [comment]
@goors, it seems the author is not going to implement the support of request customization. So, as a possible solution for our issue I can suggest you check out one component that me and my friend have created. Maybe you'll find it usefull enough. [click](https://github.com/KazanExpress/vue-simple-suggest)

**Comment by 9662** [comment]
> Some apis dont' have GET for this kind of things.

Some APIs probably need fixing.

> At company of 6mil euros, yes it is wrong

It probably is, unless the endpoint is not idempotent. Can you provide an actual example of this?

**Comment by 9662** [comment]
> I can also say that enforcing using fetch, json data format and lodash (or even REST - see GraphQL) under the hood is a very bad design too (there are many use-cases in which these "enforcement" things are a pain for a developer).

It is the developer's sole decision what use cases are going to be addressed and supported in his project. E.g., other autocomplete implementations only support retrieving data from a local model. Is that “bad design” too? But don't just tell us, **show** us how it's done man! I'm looking forward to your GraphQL-enabled, POST/PATCH/DELETE supporting, organically grown autocomplete component. 👍 And good luck maintaining that component afterwards for an audience of a few thousand users.

**Comment by Raiondesu** [comment]
@9662, I [nailed it](https://www.npmtrends.com/vue-simple-suggest-vs-vuejs-autocomplete).

**Comment by charliekassel** [comment]
I'm so happy you guys have created successful libraries.
Can we leave this as an issue tracker though and not a discussion forum please.

**Comment by charliekassel** [comment]
I have actually implemented this in v8.0.0 if you're interested.
