### ISSUE TITLE
Could you add custom templating funcionality?

### ISSUE THREAD

**Issue by martonx** [charliekassel/vuejs-autocomplete#27]
Hi,

First of all, thank you for your library, it is very useful! I would need handle and show more complex objects in autocomplete list. Could you add some functionality to use custom template like here: http://jqueryui.com/autocomplete/#custom-data

**Comment by charliekassel** [comment]
This exists already with the `resultsDisplay` prop.
You can pass in a function and it's argument will be the result item.

**Comment by martonx** [comment]
I would need not just s simple computed for display, but I need to modify the dom structure in the autocomplete result list. For example add custom class, add custom icon in the ul - li

**Comment by charliekassel** [comment]
Feel free to submit a pull request with your changes.
