### ISSUE TITLE
Clear the value after clicked

### ISSUE THREAD

**Issue by shikakunhq** [charliekassel/vuejs-autocomplete#28]
I tried using @input and this.$refs.autocomplete.clearValues(); inside @selected but not working

>  <autocomplete
            :source="apiSource"
            results-property="vn"
            placeholder=""
            @input="clearInput"
            :results-display="formatDisplay"
            @selected="vnRoute">
    </autocomplete>

> methods: {
           vnRoute (obj) {
                this.$router.push({name: 'vn', params: { id: obj.value }});
            },
            clearInput() {
                return '';
            }
}

![](https://image.ibb.co/e0ARCc/image.png)

Thank you

**Comment by charliekassel** [comment]
You need to add an `ref="autocomplete"` attribute to the component - else this won't be available in `this.$refs`
