### ISSUE TITLE
Slot for no result

### ISSUE THREAD

**Issue by jenky** [charliekassel/vuejs-autocomplete#29]
Hi,

I want to modify the no result message and perform an action when user click to "nothing found" element. Can I do it with current version. Thanks

**Comment by charliekassel** [comment]
Just added that for you here https://github.com/charliekassel/vuejs-autocomplete/pull/26/commits/2e964197c7cd75110ea93ed26bc8072f265ceb9b

Will release this in the next version shortly.

**Comment by charliekassel** [comment]
Available from vuejs-auto-complete@0.6.5

**Comment by jenky** [comment]
Thank you 👍
