### ISSUE TITLE
Allow to delay the search

### ISSUE THREAD

**Issue by DannyFeliz** [charliekassel/vuejs-autocomplete#3]
Hi, I love this package but I just wanna know if you're considering adding a `prop` to allow to specify a delay because at this moment each time you press a key the component performs the search. You can use the [_.debounce](https://lodash.com/docs/#debounce) function from [lodash](https://lodash.com/docs/) and implement it the this component.

**Comment by charliekassel** [comment]
Great, glad you like it!

I already debounce the search for 200 milliseconds. Check the source for resourceSearch method.
