### ISSUE TITLE
Dude update readme properly

### ISSUE THREAD

**Issue by popkutty** [charliekassel/vuejs-autocomplete#36]
Available props
I was using resultsValue as per readme, it wasn't working for long then looked at the code you were using results-name so changed that to results-value and started working. Please change the readme accordingly.

**Comment by charliekassel** [comment]
Open source projects are about give and take.
If you find something amiss please put in a PR then we all get better software - but don't fucking 'Dude' me when all you are doing is taking pal.

**Comment by charliekassel** [comment]
non issue - `results-value` or `resultsValue` will work as the prop defining the property to be used for the value.

**Comment by popkutty** [comment]
Thanks that was a friendly one. Sorry about that. You can delete this issue if you want. I'll use some different open source modules for this purpose.
