### ISSUE TITLE
SCSS

### ISSUE THREAD

**Issue by mits87** [charliekassel/vuejs-autocomplete#38]
Hi,

Could you move the styles to SCSS? 
It would be a great convenience.

Thx.

**Comment by charliekassel** [comment]
I don't understand why?

**Comment by mits87** [comment]
because now I don't have a choice to use your styles or not. If it will be a external file then I can or not use it. The second reason is if you use scss variables then I can change only variables and it will be work as I want. 
Now if I would like change the style some of element then I have to override your styles.

**Comment by charliekassel** [comment]
Using an external stylesheet is one thing, changing pre processor from stylus to sass is a separate thing as far as I can see - but either way I don't see how you have a choice to not use the basic styles that ship with the build.
I've tried to keep the styling as minimal and un opinionated as possible so overriding shouldn't be a problem.
