### ISSUE TITLE
Google places 

### ISSUE THREAD

**Issue by merijnvanessen** [charliekassel/vuejs-autocomplete#4]
This is the autocompletion component!
Can be easily used as to autocomplete any rest, local or specific Google maps place autocompletion 

 `<autocomplete
          source="https://maps.googleapis.com/maps/api/place/autocomplete/json?key=APIKEY&radius=500&input="
          results-property="predictions"
          input-class="input is-medium"
          results-display="formatDisplay"
          @selected="setXHRValue"
          @clear="setXHRValue({})">
        </autocomplete>`

**Comment by charliekassel** [comment]
Glad you like it!
Not sure this is an issue though - so I'm closing.
