### ISSUE TITLE
Can't add class to input

### ISSUE THREAD

**Issue by danielclariondoor** [charliekassel/vuejs-autocomplete#41]
I see there's a classInput prop, but that adds a class to the div, not the input itself, so I can't get the input to match other ones on the page.
This is a deal breaker for me.
Otherwise, looks like a nice component.

**Comment by Kovalchuk91** [comment]
+1

**Comment by tiger-mc** [comment]
+1 to this being in line with your datepicker. Thanks!

**Comment by olahat90** [comment]
Pull request sent. We are waiting for acceptance. :)

**Comment by charliekassel** [comment]
#56
