### ISSUE TITLE
property expected on result

### ISSUE THREAD

**Issue by rafa-acioly** [charliekassel/vuejs-autocomplete#42]
after trying to populate the autocomplete this error show up;

> Error in render: "Error: "name" property expected on result but is not defined."

> "name" property expected on result but is not defined.

the code is:
```js
<auto-complete
    source="http://localhost:5000/api/autocomplete/"
    input-class="is-large input"
    results-property="data">
</auto-complete>
```

i've tried to use a prop `"name"` but the same error occurs

Another question;

Is possible to remove the icons from input or use my own?

**Comment by charliekassel** [comment]
What does your response data look like?

**Comment by rafa-acioly** [comment]
@charliekassel the response is a simple array;
```
"data": [
    "Thallid",
    "Thorn Thallid",
    "Thalakos Seer",
    "Thalakos Scout",
    "Thalia's Lancers",
    "Thalakos Sentry",
    "Thallid Devourer",
    ...
],
```

**Comment by rafa-acioly** [comment]
i've changed the response to use the key `name` :)
