### ISSUE TITLE
InitialValue & initialDisplay

### ISSUE THREAD

**Issue by jayaVishwakarma** [charliekassel/vuejs-autocomplete#51]
I am trying to set an dynamic initialValue like:
```
               <autocomplete 
                    :initial-value="init_val" 
                    :initial-display="init_display"                    
                    ref="autocomplete"
                    :source="get_values"
                    resultsValue="UID"
                    results-property="Items"
                    :results-display="formatted_display"
                    :request-headers="{'Authorization': $store.getters.auth_token}"
                    @selected="select_val">
              </autocomplete>
```
if I pass static value it works but if I try adding a dynamic variable it doesn't.

**Comment by mauro-gallo** [comment]
same question

**Comment by jayaVishwakarma** [comment]
I think its because initialValue & initialDisplay is set up in mounted loads these values once when component loads. In my case I have a list and when I click edit it should be filled with saved value. I couldn't figure out a way to do it with available options so I did something I shouldn't do to temporary solve this issue:
```
this.$refs.autocomplete.$el.children[0].children[1].children[0].value = this.init_display;
this.$refs.autocomplete.$el.children[0].children[1].children[1].value = this.init_val;
```

**Comment by JMente** [comment]
I found other way to setup using component example


Template (pug)

```
component(
  v-bind:is="SELECTOR"
  :initialValue="INITIAL_VALUE"
  :initialDisplay="INITIAL_DISPLAY"
  :source="options"
  :placeholder="Search"
  @selected="onSelected"
)
```

And load the component when you request is done (javascript code)

```
axios.get("URL").then(response => {
  // Your code
  this.SELECTOR = Autocomplete
})
```

INITIAL_VALUE and INITIAL_DISPLAY can be defined before you load the component.

**Comment by ZameelAmjed** [comment]
encountering same issue any proper way to set the value dynamically?

**Comment by ptrojanowski** [comment]
This issue should be reopened.
