### ISSUE TITLE
Defining "result-property" at sublevel

### ISSUE THREAD

**Issue by Vinnythetrue** [charliekassel/vuejs-autocomplete#58]
Hi,
I'm currently trying to get the autocomplete to work with an url that returns data in some way that the content I want to autocomplete against is not at the root of the response.

Example :
`{
       "lastname":"Doe",
       "firstname":"John",
       "information":{
                      "grade":1,
                      "misc": [
                              {
                                      "id":1,
                                      "text":"Text of the ID #1"
                              },
                              {
                                      "id":2,
                                      "text":"Text of the ID #2"
                              },
                              {
                                      "id":3,
                                      "text":"Text of the ID #3"
                              },
                      ]
       }
}`

In the above example I need to autocomplete against the different "text" attributes in my "information->misc" array. Can I achieve that ?

Vinny

**Comment by charliekassel** [comment]
you can use the `results-property` prop.

results-property:

**Comment by Vinnythetrue** [comment]
I didn't figure out how to do this. I wasn't very clear about the property, but I knew about "results-property". But how can I make it point to a **sublevel** in my datasource ?
because "information.misc" won't work, for instance
