### ISSUE TITLE
HTTP headers are being converted to lower case

### ISSUE THREAD

**Issue by TNTLarsn** [charliekassel/vuejs-autocomplete#7]
```
authHeaders () {
    return {
      'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1Ni....'
    }
  }
```

the above does not work correctly because Currently fetch will toLowercase() all headers. 
(there is some discussion here https://github.com/whatwg/fetch/issues/304 about optional disabling).

[return](https://github.com/charliekassel/vuejs-autocomplete/commit/6dd457c8346dfe7874fce63db8a6e39009d42624#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) to [axios](https://www.npmjs.com/package/axios) instead

**Comment by charliekassel** [comment]
The case sensitivity of headers has not caused me a problem so far, but I understand that this may be an issue to others with server requirements outside of their management.
I'd rather not ship the library with a dependency forced upon others, so maybe the best thing would be to abstract the http library so users can supply their own but default to fetch.
Thoughts?

**Comment by TNTLarsn** [comment]
abstracting the http library is worth a try, I guess

**Comment by charliekassel** [comment]
I'm closing this as this is a fetch behaviour and so not an issue with this library per se.
I don't want to return to using an external dependency as default.
