### ISSUE TITLE
Custom ajax method

### ISSUE THREAD

**Issue by mikeburgh** [charliekassel/vuejs-autocomplete#8]
Great component!

Is there a way to implement custom logic for the AJAX ? 

So the ajax request is more complex than a single URL.. something like this for example: 

<autocomplete
		ref="autocomplete"
		:placeholder="'Search"
		:source="lookupFieldReference"
>
</autocomplete>

lookupFieldReference () { 

..Do a more complex ajax request and return the results ?

}

**Comment by charliekassel** [comment]
This should be resolved by #14
