### ISSUE TITLE
:source and :request-headers prop not allowing function

### ISSUE THREAD

**Issue by dangeroustry** [charliekassel/vuejs-autocomplete#9]
Hi,
when I try to use this part of the "Full featured example" `:source="distributionGroupsEndpoint"` I got an error: 

`Invalid prop: type check failed for prop "source". Expected String, Array, Object, got Function`

The same error is happing when I use `:request-headers="authHeaders"`

**Comment by charliekassel** [comment]
Ah sorry yes, the `authHeaders` should have been a computed property in the example.
I've amended that now in the readme.

I suspect you need to return the `source` as computed rather than a function too.
